### ISSUE TITLE
[Feature Request] Compatibility with TheRippers System Customizer. 

### ISSUE THREAD

**Issue by Orionox** [kgar/foundry-vtt-tidy-5e-sheets#235] opened 2024-01-06 01:19 UTC
Currently compatibility seems to be pretty good except for the currencies, when the system customizer changes the currencies the character sheet doesn't update to match the new currencies.

**Comment by kgar** [comment] 2024-01-17 05:25
It looks like the module requires purchase. I will contact TheRipper to inquire further.

**Comment by kgar** [comment] 2024-01-17 06:25
Reference to troubleshooting with TheRipper: https://discord.com/channels/844900867240361984/1197054285679165500

Solution: Use `CONFIG.DND5E.currencies.${currency}.abbreviation` instead of `DND5E.CurrencyAbbr${currency}`

**Comment by kgar** [comment] 2024-01-18 18:20
This has been released. When able, please give it a test and see if the issue is resolved for you.

**Comment by kgar** [comment] 2024-02-03 07:35
Closing as completed.

**Closed by kgar** 2024-02-03 07:35 UTC
Labels: compatibility
