### ISSUE TITLE
Compatibility: 5e-Sheet Resources Plus

### ISSUE THREAD

**Issue by Kharmans** [kgar/foundry-vtt-tidy-5e-sheets#246] opened 2024-01-12 15:48 UTC
This module is great, it add up to 20 new resources in sheet, but it don't work properly with this Tidy5eSheet.

On the module, you can configure individualy how much resources you want to show, but with this new Tidy5eSheet, it always show all the 20 resources.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/112586547/b3e7443b-a227-4a4a-a202-0fe188702a32)

**Comment by kgar** [comment] 2024-01-12 17:17
Thanks for reporting!
There is an ongoing effort for this module at #30 
At this time, we are waiting for a bugfix on the module itself. The author has put the compatibility code in place, but a script error is triggering before the compatibility code fixes it up for the new Tidy sheets.

**Comment by kgar** [comment] 2024-01-12 17:18
Closing as duplicate of #30

**Comment by kgar** [comment] 2024-01-12 17:18
Still figuring out how to closing issues correctly :/

**Comment by Kharmans** [comment] 2024-02-03 14:05
Yeah, I see the new feature in dnd5e 3.0. I think you can just drop this module.

**Comment by kgar** [comment] 2024-02-07 05:29
Closing as no longer planned, due to dnd5e 3.0.0's new direction regarding resources.

**Closed by kgar** 2024-02-07 05:29 UTC
Labels: compatibility
